# Generated by Django 5.2.8 on 2026-02-15 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='homeworks', to='lessons.lessons')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='user.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('class_grade', models.CharField(blank=True, choices=[('first_grade', 'First Grade'), ('second_grade', 'Second Grade'), ('third_grade', 'Third Grade'), ('fourth_grade', 'Fourth Grade'), ('fifth_grade', 'Fifth Grade'), ('sixth_grade', 'Sixth Grade'), ('seventh_grade', 'Seventh Grade'), ('eighth_grade', 'Eighth Grade'), ('ninth_grade', 'Ninth Grade'), ('tenth_grade', 'Tenth Grade'), ('eleventh_grade', 'Eleventh Grade'), ('twelfth_grade', 'Twelfth Grade')], max_length=100, null=True)),
                ('teacher', models.ManyToManyField(blank=True, related_name='classrooms', to='user.teacherprofile')),
                ('home_work', models.ManyToManyField(blank=True, to='students.homework')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, choices=[('first_grade', 'First Grade'), ('second_grade', 'Second Grade'), ('third_grade', 'Third Grade'), ('fourth_grade', 'Fourth Grade'), ('fifth_grade', 'Fifth Grade'), ('sixth_grade', 'Sixth Grade'), ('seventh_grade', 'Seventh Grade'), ('eighth_grade', 'Eighth Grade'), ('ninth_grade', 'Ninth Grade'), ('tenth_grade', 'Tenth Grade'), ('eleventh_grade', 'Eleventh Grade'), ('twelfth_grade', 'Twelfth Grade')], max_length=100, null=True)),
                ('report_card', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('class_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.classroom')),
                ('lessons', models.ManyToManyField(to='lessons.lessons')),
                ('parents', models.ManyToManyField(blank=True, related_name='students', to='user.parentprofile')),
                ('teacher', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='user.teacherprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
