# Generated by Django 5.2.8 on 2026-02-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('students', '0002_alter_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='lessons',
            field=models.ManyToManyField(blank=True, to='lessons.lessons'),
        ),
    ]
