# Generated by Django 5.2.8 on 2026-02-18 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_classroom_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='course',
        ),
    ]
