# Generated by Django 5.2.8 on 2026-02-18 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='lessons',
                    unique_together=set(),
                ),
            ],
        ),
        migrations.AddField(
            model_name='lessons',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.period'),
        ),
        migrations.AddConstraint(
            model_name='lessons',
            constraint=models.UniqueConstraint(fields=('stage', 'day', 'period'), name='unique_stage_day_period'),
        ),
    ]
