# Generated by Django 5.2.8 on 2026-02-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_period_alter_lessons_unique_together_lessons_period_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS lessons_day (
                id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
                name VARCHAR(20) NOT NULL,
                "order" INTEGER unsigned NOT NULL
            );
            CREATE TABLE IF NOT EXISTS lessons_stage (
                id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
                name VARCHAR(50) NOT NULL
            );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20, unique=True),
        ),
        migrations.AddConstraint(
            model_name='day',
            constraint=models.CheckConstraint(condition=models.Q(('name__in', ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Saturday', 'Sunday'])), name='day_name_without_friday'),
        ),
    ]
